export const sampleCourses = [
  {
    id: 1,
    title: "React for Beginners",
    instructor: "Jane Doe",
    category: "Web Development",
    students: 120,
    rating: 4.7,
    price: "$49",
    description: "Learn the basics of React.",
    features: ["JSX", "Components", "Hooks"],
  },
  {
    id: 2,
    title: "Python Data Science",
    instructor: "John Smith",
    category: "Data Science",
    students: 95,
    rating: 4.8,
    price: "$59",
    description: "Data analysis and visualization with Python.",
    features: ["Pandas", "NumPy", "Matplotlib"],
  },
  {
    id: 3,
    title: "UI/UX Design Essentials",
    instructor: "Emily Clark",
    category: "Design",
    students: 80,
    rating: 4.6,
    price: "$39",
    description: "Fundamentals of user interface and experience design.",
    features: ["Wireframes", "Prototyping", "Figma"],
  },
  {
    id: 4,
    title: "Advanced JavaScript",
    instructor: "Michael Lee",
    category: "Web Development",
    students: 110,
    rating: 4.9,
    price: "$69",
    description: "Deep dive into modern JavaScript features.",
    features: ["ES6+", "Async/Await", "Closures"],
  },
  {
    id: 5,
    title: "Machine Learning with Python",
    instructor: "Sarah Kim",
    category: "Data Science",
    students: 130,
    rating: 4.8,
    price: "$79",
    description: "Build and train machine learning models.",
    features: ["Scikit-learn", "Regression", "Classification"],
  },
  {
    id: 6,
    title: "Responsive Web Design",
    instructor: "David Brown",
    category: "Web Development",
    students: 75,
    rating: 4.5,
    price: "$45",
    description: "Create websites that look great on any device.",
    features: ["Flexbox", "Grid", "Media Queries"],
  },
  {
    id: 7,
    title: "Photoshop for Beginners",
    instructor: "Anna White",
    category: "Design",
    students: 60,
    rating: 4.4,
    price: "$35",
    description: "Learn to edit and enhance photos.",
    features: ["Layers", "Retouching", "Filters"],
  },
  {
    id: 8,
    title: "Node.js API Development",
    instructor: "Chris Green",
    category: "Web Development",
    students: 90,
    rating: 4.7,
    price: "$55",
    description: "Build RESTful APIs using Node.js.",
    features: ["Express", "Routing", "Middleware"],
  },
  {
    id: 9,
    title: "Statistics for Data Science",
    instructor: "Olivia Black",
    category: "Data Science",
    students: 85,
    rating: 4.6,
    price: "$50",
    description: "Essential statistics concepts for data analysis.",
    features: ["Probability", "Distributions", "Hypothesis Testing"],
  },
  {
    id: 10,
    title: "Logo Design Masterclass",
    instructor: "Mark Grey",
    category: "Design",
    students: 70,
    rating: 4.5,
    price: "$42",
    description: "Create professional logos from scratch.",
    features: ["Branding", "Illustrator", "Typography"],
  },
];